language: generic

env:
  global:
    - PYTHON_VERSION=py37
    - INSTALL_DIR=$HOME/HyperSpy-bundle

os:
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; 
     PLATFORM='MacOSX';
    else
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
     PLATFORM='Linux';
    fi
  - chmod +x miniconda.sh;
    ./miniconda.sh -b -p $HOME/miniconda;
    source $HOME/miniconda/bin/activate;

install:
  - conda update -y conda;
  - conda install -yq constructor

script:
  # Create the anaconda based hyperspy bundle
  - constructor -v
  - conda deactivate

  # Rename the output file which can have .sh or .pkg extension
  - ls
  # We need to "rev" twice to retrieve the last field of the "cut"
  - EXT=`echo HyperSpy-* | rev | cut -d'.' -f1 | rev`
  - echo $EXT
  - BUILD_NAME=HyperSpy-bundle-${TRAVIS_TAG}-${PYTHON_VERSION}-${PLATFORM}-64bit.${EXT}
  - mv HyperSpy-*.${EXT} $BUILD_NAME
  - ls

  # Install the build in the subfolder "HyperSpy-bundle"
  - if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then
     sudo installer -pkg $BUILD_NAME -target /;
     source /HyperSpy-bundle/bin/activate;
    else
     bash $BUILD_NAME -b -p $INSTALL_DIR;
     source $INSTALL_DIR/bin/activate;
    fi
  - ls $HOME
  - ls $INSTALL_DIR

  # Check the installation and environment 
  - conda info
  - conda list

  # Re-run tests in the created anaconda build.
  - conda install -yq -c conda-forge pytest pytest-mpl
  - export MPLBACKEND=agg
  # - pytest --mpl --pyargs hyperspy

deploy:
  provider: releases
  api_key:
    # ericpre:
    secure: "HmYq6EvfcP2H16Vew3QKCz5d/02xxyAtYAfvycvBk0wiTXw0Bt1dBGn8A8xgzpUU0GUgCqeiSp57JT3c+bwXPF04IQ3gDmoB2203R/Rsj35gy6owaMyVGTkYa2VQTByJLXVlFuNnL/LPOhHKBI/y+22xBtvdXrE5DhuzIHR3t0XpLk7TYurXsv4nBIWwptgq1eTUDf+9tNIyyrW9J6cAazTXPIKUp0QaRUx699FaI4Fobn0Mp0hT0X6jodo0qknSknVuYGP695maadIr+HavfIYwrxFm45Tc1DP0SMA0br4ZnetkrISBH/4AlhSCmxJAkODU/xuAmz8cxgYqrxXTIZ/pJh/MGY2TdibUeCkp9pa0LFOvmZj6lt/9z64Sz9dRmgc2CiZ3l0cqXufbV89DZjuJMvVeweJXYoq01F7WJqYbJBH6wylri4GV4Aol4I/WLUCUHrPsPBEGClDB/RLXf7LPaGwpmQp5gfVvD48+258OXfz4refKKnRsjV3hpD5vLkhbEe2jk8zYmENNL57n8vzowCcMP9ND6hrTQ39LGGrlwO/w9raRGtxQB4W8+Tw+uGeE5DaH7CMgsGw2Cbgdu5im8Lv5HJxGv3NqBT6jZybcmXGIIsoZt3cCZ/dGjotNfHHylR6jUtFrnmqSgByGLeZab3zhIXgj041NiBfUWgY="
  file: $BUILD_NAME
  skip_cleanup: true
  on:
    tags: true
