
shallow_clone: true

environment:

  matrix:
     - MINICONDA: "C:\\Miniconda36"
       PYTHON_VERSION: "py36"
       PYTHON_ARCH: "32bit"
  
     - MINICONDA: "C:\\Miniconda36-x64"
       PYTHON_VERSION: "py36"
       PYTHON_ARCH: "64bit"

init:
  - "set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\\HyperSpy-bundle"
  - "ECHO %MINICONDA%"
  - "ECHO %APPVEYOR_BUILD_FOLDER%"
  - "ECHO %INSTALL_DIR%"
  - "ECHO %CMD_IN_ENV%"

install:
  - 'set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%'
  - conda install -yq --only-deps constructor
  - pip install https://github.com/ericpre/constructor/archive/ignore_noarch_python.zip

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Create the anaconda based hyperspy bundle
  - constructor -v .
  - deactivate
  - 'set BUNDLE_INST_NAME=HyperSpy-bundle-%APPVEYOR_REPO_TAG_NAME%-%PYTHON_VERSION%-Windows%PYTHON_ARCH%.exe'
  - 'ren HyperSpy-Bundle-* %BUNDLE_INST_NAME%'

  # Install the build
  - 'start /wait "" %BUNDLE_INST_NAME% /S /D=%INSTALL_DIR%'
  - dir
  - dir %INSTALL_DIR%

  # Check installed package
  - set HYPERSPY_BUNDLE_SCRIPTS_PATH=%INSTALL_DIR%\\Scripts
  - echo %HYPERSPY_BUNDLE_SCRIPTS_PATH%
  - dir %HYPERSPY_BUNDLE_SCRIPTS_PATH%
  - cd %HYPERSPY_BUNDLE_SCRIPTS_PATH%
  - conda list
  - 'conda install -yq -c conda-forge pytest pytest-mpl'

  # Re-run tests in the created anaconda build.
  - 'set MPLBACKEND=agg'
  - 'pytest --mpl --pyargs hyperspy'

artifacts:
  - path: '*.exe'

deploy:
  provider: GitHub
  auth_token:
    #   to266:
    #secure: ptV5Dkz3pSVdjD0qRDpxJgjVlddFtleZ+B+c2X1Fg67P8OX3bHWVktRmlj6hfLhM
    #   vidartf:
    #secure: KwAfARhGEqOnZHltPB6kKu8xmnoiGSk7NMYJBIEbWvFCuVnepoPV7ZcIjUN3pUpK
    #   sem-geologist:
    #secure: RRqUkx9H5VuFNITmm+YzgB0qnqgVGPH1yrPVxb4oCD+FAjcTch2WZAiPEKn4L6w6
    #   ericpre:
    secure: ae8XsPI+vKJI9AWm0r9+ec71CIkXcnCHlNIQ57v+87hh5k1xuAAxIOi1CFKEmmZv
  artifact: /.*\.exe/  # upload installers to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
