
shallow_clone: true

environment:

  matrix:
     - MINICONDA: "C:\\Miniconda36"
     - MINICONDA: "C:\\Miniconda36-x64"

init:
  - "ECHO %MINICONDA%"
  - "ECHO %APPVEYOR_BUILD_FOLDER%"
  - "ECHO %CMD_IN_ENV%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%" 
  - appveyor AddMessage "Installing hyperspy-bundle..."
  - conda install -yq constructor"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Create the anaconda based hyperspy bundle
  - constructor .

  # Install the build

  # Re-run tests in the created anaconda build.
  - appveyor AddMessage "Tests finished! Pushing to GitHub..."
  - appveyor PushArtifact C:\projects\hyperspy-bundle\*.exe

on_failure:
  # In case, the tests fail, we still push the installer to debug the failure if necessary.
  - appveyor PushArtifact C:\projects\hyperspy-bundle\*.exe

deploy:
  provider: GitHub
  auth_token:
    #   to266:
    #secure: ptV5Dkz3pSVdjD0qRDpxJgjVlddFtleZ+B+c2X1Fg67P8OX3bHWVktRmlj6hfLhM
    #   vidartf:
    #secure: KwAfARhGEqOnZHltPB6kKu8xmnoiGSk7NMYJBIEbWvFCuVnepoPV7ZcIjUN3pUpK
    #   sem-geologist:
    #secure: RRqUkx9H5VuFNITmm+YzgB0qnqgVGPH1yrPVxb4oCD+FAjcTch2WZAiPEKn4L6w6
    #   ericpre:
    secure: ae8XsPI+vKJI9AWm0r9+ec71CIkXcnCHlNIQ57v+87hh5k1xuAAxIOi1CFKEmmZv
  artifact: /.*\.exe/  # upload installers to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
