name: Release

on: [push]
  #push:
  #   Sequence of patterns matched against refs/tags
  #  tags:
  #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    name: Create Release (on tag only)
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: ${{ matrix.config.os }}
    if: startsWith(github.ref, 'refs/tags/')
    needs: create_release
    runs-on: ${{ matrix.config.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos
            INSTALLER_EXTENSION: pkg
          - os: ubuntu
            INSTALLER_EXTENSION: sh
          - os: windows
            INSTALLER_EXTENSION: exe
    env:
      MPLBACKEND: agg
      TEST_DEPS: pytest pytest-mpl
      LIB_TO_TEST: hyperspy

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.7

      - shell: bash -l {0}
        name: Conda info
        run: |
          conda info
          conda list

      - shell: bash -l {0}
        name: Install constructor
        run: |
          conda install constructor
          pip install https://github.com/conda/constructor/archive/master.zip --no-deps

      - shell: bash -l {0}
        name: Build distribution
        run: |
          constructor -v conda_distribution

      - shell: bash -l {0}
        name: Set asset name
        run: |
          fname=(HyperSpy-*.${{ matrix.config.INSTALLER_EXTENSION }})
          echo ::set-env name=asset_name::$fname
          echo $fname

      - name: Get hash
        run: |
          shasum -a 256 ${{ env.asset_name }}

      - name: Install new distribution (Linux)
        if: runner.os == 'linux'
        env:
          install_dir: '${{ github.workspace }}/new_distribution'
        run: |
          echo ::set-env name=install_dir::${{ env.install_dir }}
          bash ${{ env.asset_name }} -b -p ${{ env.install_dir }}

      - name: Install new distribution (MacOS)
        if: runner.os == 'macos'
        run: |
          echo "::set-env name=install_dir::/Users/runner"
          installer -pkg ${{ env.asset_name }} -target CurrentUserHomeDirectory

      - name: Install new distribution (Windows)
        if: runner.os == 'windows'
        env:
          install_dir: '${{ github.workspace }}\new_distribution'
        shell: powershell
        run: |
          echo "::set-env name=install_dir::${{ env.install_dir }}"
          Start-Process -Wait -FilePath ${{ env.asset_name }} -ArgumentList "/S /AddToPath=0 /RegisterPython=0 /NoScripts=1 /D=${{ env.install_dir }}"

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ env.asset_name }}

      - shell: bash -l {0}
        name: Info new distribution
        run: |
          conda activate "${{ env.install_dir }}"
          conda info
          conda list

      - shell: bash -l {0}
        name: Test new distribution
        run: |
          conda activate "${{ env.install_dir }}"
          conda install ${{ env.TEST_DEPS }}
          pytest --pyargs ${{ env.LIB_TO_TEST }}

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: skx/github-action-publish-binaries@release-0.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: ${{ env.asset_name }}

  build_portable:
    name: windows (Portable)
    needs: create_release
    runs-on: windows-latest
    env:
      WP_URL: https://github.com/winpython/winpython/releases/download/2.3.20200530/Winpython64-3.8.3.0cod.exe
      WP_SHA256: f3870e8570b5f3e31821756089af1237859a6db8a971c1fea14a560d4c85a314
      WP_EXE: winpython.exe
      WP_DIR_NAME: WPy64-3830
      INSTALLER_NAME: HyperSpy-bundle-TAG-Windows-x86_64-Portable.exe
      MPLBACKEND: agg
      TEST_DEPS: pytest pytest-mpl
      LIB_TO_INSTALL: hyperspy pyxem atomap
      LIB_TO_TEST: hyperspy

    steps:
      - name: Download Winpython
        run: |
          Invoke-WebRequest -OutFile ${{ env.WP_EXE }} ${{ env.WP_URL }}
          ls
          $file_hash = (Get-FileHash "${{ env.WP_EXE }}" ).Hash
          $file_hash 
          if ($file_hash -ne "${{ env.WP_SHA256 }}") { exit(1) }
          $file_hash = (Get-FileHash ${{ env.WP_EXE }} ).Hash
          $file_hash 

      - name: Extract Winpython
        run: |
          .\${{ env.WP_EXE }} -y | Out-Null
          ls
          ls ${{ env.WP_DIR_NAME }}

      - name: Install libraries
        run: |
          "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pip install wheel
          pip install ${{ env.LIB_TO_INSTALL }}

      - name: Create installer
        run: |
          7za -mx5 -sfx7z.sfx a "{{ env.INSTALLER_NAME }}" "{{ env.WP_DIR_NAME }}"
          ls

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ env.INSTALLER_NAME }}

      - name: Install testing libraries
        run: |
          "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pip install ${{ env.TEST_DEPS }}

      - name: Run test suite
        run: |
          "${{ env.WP_DIR_NAME }}\scripts\env.bat"
          pytest --pyargs ${{ env.LIB_TO_TEST }}


